[package]
name = "native-launcher"
version = "1.0.0"
edition = "2021"
workspace = "../.."

[dependencies]
colorwheel_bump = { package = "colorwheel_bump", path = "../.." }
bevy = "0.8"
image = "0.24.3"
winit = "0.26.1"